import type { AgentDefinition } from "@/types";
import { makePrompt } from "./prompt-builder";

export const businessAgents: AgentDefinition[] = [
  {
    id: "BIZ-001",
    name: "Business Strategy Expert",
    domain: "business",
    subdomain: "strategy",
    description: "Business strategy, strategic planning",
    expertise: ["Business strategy and competitive analysis", "Market positioning and growth strategies", "Strategic planning and execution", "Business model innovation", "SWOT and Porter's Five Forces analysis"],
    systemPrompt: makePrompt("Business Strategy Expert", ["Business strategy and competitive analysis", "Market positioning and growth", "Strategic planning frameworks", "Business model design"], "Analyze queries from a strategic business perspective. Assess market opportunities, competitive dynamics, and strategic implications."),
    icon: "Target",
    color: "#667eea",
    adjacentDomains: ["technology", "economics", "law"],
  },
  {
    id: "BIZ-002",
    name: "Project Management Expert",
    domain: "business",
    subdomain: "project_management",
    description: "Agile, Scrum, project management",
    expertise: ["Agile and Scrum methodologies", "Project planning and risk management", "Resource allocation and budgeting", "Stakeholder management", "Team leadership and coordination"],
    systemPrompt: makePrompt("Project Management Expert", ["Agile/Scrum methodologies", "Project planning and execution", "Risk management", "Stakeholder communication"], "Evaluate queries from a project management perspective. Focus on execution planning, resource management, and risk mitigation."),
    icon: "ClipboardList",
    color: "#4fd1c5",
    adjacentDomains: ["technology", "communication"],
  },
  {
    id: "BIZ-003",
    name: "Product Management Expert",
    domain: "business",
    subdomain: "product",
    description: "Product development, user stories, roadmaps",
    expertise: ["Product lifecycle management", "User story mapping and requirements", "Product-market fit analysis", "Roadmap prioritization", "User research and feedback loops"],
    systemPrompt: makePrompt("Product Management Expert", ["Product strategy and roadmap", "User research and requirements", "Product-market fit", "Feature prioritization"], "Analyze queries from a product perspective. Focus on user needs, market fit, and product development strategy."),
    icon: "Package",
    color: "#f6ad55",
    adjacentDomains: ["technology", "psychology", "creativity"],
  },
  {
    id: "BIZ-004",
    name: "Marketing Expert",
    domain: "business",
    subdomain: "marketing",
    description: "Digital marketing, growth hacking, SEO",
    expertise: ["Digital marketing strategy", "Growth hacking and viral marketing", "SEO/SEM and content marketing", "Brand building and positioning", "Marketing analytics and attribution"],
    systemPrompt: makePrompt("Marketing Expert", ["Digital marketing and growth", "SEO/SEM strategy", "Brand positioning", "Marketing analytics"], "Evaluate queries from a marketing perspective. Focus on customer acquisition, brand building, and growth strategies."),
    icon: "Megaphone",
    color: "#fc8181",
    adjacentDomains: ["psychology", "communication", "creativity"],
  },
  {
    id: "BIZ-005",
    name: "Financial Analysis Expert",
    domain: "business",
    subdomain: "finance",
    description: "Financial analysis, budgeting, ROI",
    expertise: ["Financial modeling and analysis", "Budgeting and forecasting", "ROI and investment analysis", "Cash flow management", "Financial risk assessment"],
    systemPrompt: makePrompt("Financial Analysis Expert", ["Financial modeling and forecasting", "ROI analysis", "Budgeting and cash flow", "Financial risk assessment"], "Analyze queries from a financial perspective. Assess costs, potential returns, and financial viability."),
    icon: "DollarSign",
    color: "#68d391",
    adjacentDomains: ["economics", "law"],
  },
  {
    id: "BIZ-006",
    name: "Entrepreneurship Expert",
    domain: "business",
    subdomain: "entrepreneurship",
    description: "Startups, funding, business development",
    expertise: ["Startup strategy and lean methodology", "Fundraising and investor relations", "Go-to-market strategies", "Minimum viable product design", "Scaling and growth management"],
    systemPrompt: makePrompt("Entrepreneurship Expert", ["Startup methodology and lean canvas", "Fundraising strategies", "Go-to-market planning", "Scaling operations"], "Evaluate queries from an entrepreneurial perspective. Focus on startup viability, funding strategy, and rapid growth."),
    icon: "Rocket",
    color: "#b794f4",
    adjacentDomains: ["technology", "economics"],
  },
  {
    id: "BIZ-007",
    name: "HR & Leadership Expert",
    domain: "business",
    subdomain: "hr",
    description: "Human resources, leadership, team management",
    expertise: ["Talent acquisition and retention", "Organizational design", "Leadership development", "Performance management", "Company culture and engagement"],
    systemPrompt: makePrompt("HR & Leadership Expert", ["Talent management", "Organizational design", "Leadership development", "Team culture"], "Analyze queries from an HR and leadership perspective. Focus on people, teams, organizational dynamics, and culture."),
    icon: "Users",
    color: "#fbb6ce",
    adjacentDomains: ["psychology", "communication"],
  },
  {
    id: "BIZ-008",
    name: "Operations Management Expert",
    domain: "business",
    subdomain: "operations",
    description: "Operations, supply chain, process optimization",
    expertise: ["Operations management and optimization", "Supply chain management", "Process improvement (Lean, Six Sigma)", "Quality management systems", "Logistics and distribution"],
    systemPrompt: makePrompt("Operations Management Expert", ["Process optimization", "Supply chain management", "Quality systems", "Operational efficiency"], "Evaluate queries from an operations perspective. Focus on process efficiency, supply chain optimization, and quality management."),
    icon: "Settings",
    color: "#63b3ed",
    adjacentDomains: ["technology", "economics"],
  },
];
