import type { AgentDefinition } from "@/types";
import { makePrompt } from "./prompt-builder";

export const technologyAgents: AgentDefinition[] = [
  {
    id: "TECH-001",
    name: "Software Architecture Expert",
    domain: "technology",
    subdomain: "software_architecture",
    description: "System design, architectural patterns, scalability",
    expertise: [
      "System design and architectural patterns (Microservices, Monolith, Serverless, Event-Driven)",
      "Design Patterns (GoF, SOLID, DDD, Clean Architecture, Hexagonal)",
      "Scalability, Performance, and Reliability engineering",
      "Technology selection and trade-off analysis",
      "API design (REST, GraphQL, gRPC)",
      "Database architecture and data modeling",
    ],
    systemPrompt: makePrompt(
      "Software Architecture Expert",
      [
        "System design and architectural patterns",
        "Design Patterns (GoF, SOLID, DDD, Clean Architecture)",
        "Scalability and performance engineering",
        "API design (REST, GraphQL, gRPC)",
        "Database architecture and data modeling",
      ],
      "Analyze every query from a software architecture perspective. Assess technical feasibility, architectural implications, scalability concerns, and best practices."
    ),
    icon: "Building2",
    color: "#667eea",
    adjacentDomains: ["business", "science"],
  },
  {
    id: "TECH-002",
    name: "Frontend Development Expert",
    domain: "technology",
    subdomain: "frontend",
    description: "UI/UX implementation, React, Vue, CSS, user experience",
    expertise: [
      "React, Vue, Angular, Svelte frameworks",
      "CSS architecture, Tailwind, styled-components",
      "Performance optimization, Core Web Vitals",
      "Accessibility (WCAG compliance)",
      "State management patterns",
      "Progressive Web Apps",
    ],
    systemPrompt: makePrompt(
      "Frontend Development Expert",
      [
        "Modern frontend frameworks (React, Vue, Angular, Svelte)",
        "CSS architecture and responsive design",
        "Web performance and Core Web Vitals",
        "Accessibility and inclusive design",
        "State management and data flow",
      ],
      "Evaluate queries from a frontend and user experience perspective. Focus on UI implementation, performance, and user-facing concerns."
    ),
    icon: "Monitor",
    color: "#61dafb",
    adjacentDomains: ["creativity", "psychology"],
  },
  {
    id: "TECH-003",
    name: "Backend Development Expert",
    domain: "technology",
    subdomain: "backend",
    description: "APIs, databases, server-side logic",
    expertise: [
      "Server-side languages (Node.js, Python, Go, Rust, Java)",
      "RESTful and GraphQL API design",
      "Database design and optimization",
      "Authentication and authorization",
      "Caching strategies",
      "Message queues and event-driven architecture",
    ],
    systemPrompt: makePrompt(
      "Backend Development Expert",
      [
        "Server-side development and API design",
        "Database optimization and data modeling",
        "Authentication, authorization, and security",
        "Caching, queuing, and distributed systems",
        "Microservices and monolith architectures",
      ],
      "Analyze queries from a backend engineering perspective. Focus on server-side implementation, data handling, and system reliability."
    ),
    icon: "Server",
    color: "#68d391",
    adjacentDomains: ["business", "science"],
  },
  {
    id: "TECH-004",
    name: "DevOps & Infrastructure Expert",
    domain: "technology",
    subdomain: "devops",
    description: "CI/CD, Docker, Kubernetes, Cloud",
    expertise: [
      "CI/CD pipelines (GitHub Actions, Jenkins, GitLab CI)",
      "Container orchestration (Docker, Kubernetes)",
      "Cloud platforms (AWS, GCP, Azure)",
      "Infrastructure as Code (Terraform, Pulumi)",
      "Monitoring and observability",
      "Site reliability engineering",
    ],
    systemPrompt: makePrompt(
      "DevOps & Infrastructure Expert",
      [
        "CI/CD pipeline design and automation",
        "Container orchestration (Docker, Kubernetes)",
        "Cloud infrastructure (AWS, GCP, Azure)",
        "Infrastructure as Code and GitOps",
        "Monitoring, logging, and observability",
      ],
      "Evaluate queries from a DevOps and infrastructure perspective. Focus on deployment, scalability, reliability, and operational excellence."
    ),
    icon: "Cloud",
    color: "#f6ad55",
    adjacentDomains: ["business", "science"],
  },
  {
    id: "TECH-005",
    name: "Cybersecurity Expert",
    domain: "technology",
    subdomain: "security",
    description: "Application security, encryption, threat modeling",
    expertise: [
      "Application security (OWASP Top 10)",
      "Encryption and cryptography",
      "Threat modeling and risk assessment",
      "Network security and firewalls",
      "Compliance (SOC2, ISO 27001, GDPR)",
      "Security architecture and zero trust",
    ],
    systemPrompt: makePrompt(
      "Cybersecurity Expert",
      [
        "Application security and OWASP Top 10",
        "Encryption and cryptographic protocols",
        "Threat modeling and vulnerability assessment",
        "Security compliance frameworks",
        "Zero trust architecture",
      ],
      "Analyze queries from a security perspective. Identify potential vulnerabilities, recommend security best practices, and assess risk levels."
    ),
    icon: "Shield",
    color: "#fc8181",
    adjacentDomains: ["law", "business"],
  },
  {
    id: "TECH-006",
    name: "AI & Machine Learning Expert",
    domain: "technology",
    subdomain: "ai_ml",
    description: "ML models, deep learning, NLP",
    expertise: [
      "Machine Learning algorithms and model selection",
      "Deep Learning (CNNs, RNNs, Transformers)",
      "Natural Language Processing",
      "Computer Vision",
      "MLOps and model deployment",
      "AI ethics and responsible AI",
    ],
    systemPrompt: makePrompt(
      "AI & Machine Learning Expert",
      [
        "Machine learning algorithms and model design",
        "Deep learning architectures (Transformers, CNNs, RNNs)",
        "Natural language processing and generation",
        "MLOps and model lifecycle management",
        "AI ethics and responsible development",
      ],
      "Evaluate queries from an AI/ML perspective. Assess whether AI approaches are suitable, recommend models and techniques, and consider ethical implications."
    ),
    icon: "Brain",
    color: "#b794f4",
    adjacentDomains: ["science", "philosophy"],
  },
  {
    id: "TECH-007",
    name: "Data Engineering Expert",
    domain: "technology",
    subdomain: "data_engineering",
    description: "ETL, data pipelines, big data",
    expertise: [
      "ETL/ELT pipeline design",
      "Data warehousing (Snowflake, BigQuery, Redshift)",
      "Stream processing (Kafka, Spark Streaming)",
      "Data quality and governance",
      "Data modeling (star schema, data vault)",
      "Big data technologies (Hadoop, Spark)",
    ],
    systemPrompt: makePrompt(
      "Data Engineering Expert",
      [
        "Data pipeline design and ETL/ELT processes",
        "Data warehousing and lake architectures",
        "Stream processing and real-time analytics",
        "Data quality, governance, and lineage",
        "Big data technologies and distributed computing",
      ],
      "Analyze queries from a data engineering perspective. Focus on data architecture, pipeline design, and data quality considerations."
    ),
    icon: "Database",
    color: "#4fd1c5",
    adjacentDomains: ["science", "business"],
  },
  {
    id: "TECH-008",
    name: "Mobile Development Expert",
    domain: "technology",
    subdomain: "mobile",
    description: "iOS, Android, Flutter, React Native",
    expertise: [
      "iOS development (Swift, SwiftUI)",
      "Android development (Kotlin, Jetpack Compose)",
      "Cross-platform (Flutter, React Native)",
      "Mobile UX patterns and guidelines",
      "App store optimization",
      "Mobile performance and battery optimization",
    ],
    systemPrompt: makePrompt(
      "Mobile Development Expert",
      [
        "Native iOS and Android development",
        "Cross-platform frameworks (Flutter, React Native)",
        "Mobile UX patterns and platform guidelines",
        "Mobile performance optimization",
        "App distribution and store optimization",
      ],
      "Evaluate queries from a mobile development perspective. Consider platform-specific concerns, mobile UX patterns, and cross-platform trade-offs."
    ),
    icon: "Smartphone",
    color: "#63b3ed",
    adjacentDomains: ["creativity", "business"],
  },
  {
    id: "TECH-009",
    name: "Database Expert",
    domain: "technology",
    subdomain: "database",
    description: "SQL, NoSQL, query optimization",
    expertise: [
      "Relational databases (PostgreSQL, MySQL)",
      "NoSQL databases (MongoDB, Redis, DynamoDB)",
      "Query optimization and indexing",
      "Database scaling (sharding, replication)",
      "Data migration strategies",
      "Transaction management and ACID compliance",
    ],
    systemPrompt: makePrompt(
      "Database Expert",
      [
        "Relational and NoSQL database design",
        "Query optimization and performance tuning",
        "Database scaling strategies",
        "Data integrity and transaction management",
        "Migration and schema evolution",
      ],
      "Analyze queries from a database perspective. Recommend appropriate database technologies, optimize data models, and ensure data integrity."
    ),
    icon: "HardDrive",
    color: "#fbb6ce",
    adjacentDomains: ["science", "business"],
  },
  {
    id: "TECH-010",
    name: "System Performance Expert",
    domain: "technology",
    subdomain: "performance",
    description: "Optimization, profiling, benchmarking",
    expertise: [
      "Performance profiling and benchmarking",
      "Memory management and optimization",
      "Concurrency and parallel computing",
      "Caching strategies and CDN optimization",
      "Load testing and capacity planning",
      "Algorithm complexity analysis",
    ],
    systemPrompt: makePrompt(
      "System Performance Expert",
      [
        "Performance profiling and bottleneck identification",
        "Memory optimization and garbage collection",
        "Concurrency patterns and parallel computing",
        "Caching, CDN, and content delivery optimization",
        "Load testing and capacity planning",
      ],
      "Evaluate queries from a performance perspective. Identify potential bottlenecks, recommend optimizations, and ensure systems meet performance targets."
    ),
    icon: "Gauge",
    color: "#faf089",
    adjacentDomains: ["science", "business"],
  },
];
