"use client";

import { useState, useEffect, useCallback } from "react";
import { Copy, Download, FileText, Check } from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";

interface ExportModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  query: string;
  response: string;
  agentCount?: number;
  consensusScore?: number;
}

function buildMarkdown({
  query,
  response,
  agentCount,
  consensusScore,
}: Omit<ExportModalProps, "open" | "onOpenChange">): string {
  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  let md = `# Deep Thinking AI - Council Response\n\n`;
  md += `## Query\n${query}\n\n`;
  md += `## Response\n${response}\n\n`;

  if (agentCount !== undefined || consensusScore !== undefined) {
    md += `## Council Details\n`;
    if (agentCount !== undefined) md += `- Agents: ${agentCount}\n`;
    if (consensusScore !== undefined)
      md += `- Consensus Score: ${Math.round(consensusScore * 100)}%\n`;
    md += `\n`;
  }

  md += `---\nGenerated by Deep Thinking AI on ${date}\n`;
  return md;
}

function stripMarkdown(md: string): string {
  return md
    .replace(/^#{1,6}\s+/gm, "")
    .replace(/\*\*(.*?)\*\*/g, "$1")
    .replace(/\*(.*?)\*/g, "$1")
    .replace(/`{1,3}[^`]*`{1,3}/g, (m) =>
      m.replace(/^`{1,3}/, "").replace(/`{1,3}$/, "")
    )
    .replace(/^\s*[-*+]\s+/gm, "- ")
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    .replace(/^---$/gm, "")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

function triggerDownload(content: string, filename: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

type FeedbackKey = "copy" | "md" | "txt" | null;

export function ExportModal({
  open,
  onOpenChange,
  query,
  response,
  agentCount,
  consensusScore,
}: ExportModalProps) {
  const [feedback, setFeedback] = useState<FeedbackKey>(null);

  useEffect(() => {
    return () => {
      // Cleanup any pending feedback timer when modal closes
      setFeedback(null);
    };
  }, [open]);

  const showFeedback = useCallback((key: FeedbackKey) => {
    setFeedback(key);
    setTimeout(() => setFeedback(null), 2000);
  }, []);

  const markdown = buildMarkdown({ query, response, agentCount, consensusScore });

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(markdown);
      showFeedback("copy");
    } catch {
      // Fallback
      const textarea = document.createElement("textarea");
      textarea.value = markdown;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
      showFeedback("copy");
    }
  };

  const handleDownloadMd = () => {
    triggerDownload(markdown, "council-response.md", "text/markdown");
    showFeedback("md");
  };

  const handleDownloadTxt = () => {
    const plain = stripMarkdown(markdown);
    triggerDownload(plain, "council-response.txt", "text/plain");
    showFeedback("txt");
  };

  const actions = [
    {
      key: "copy" as const,
      label: "Copy to Clipboard",
      description: "Copy the full response as Markdown",
      icon: Copy,
      successIcon: Check,
      onClick: handleCopy,
    },
    {
      key: "md" as const,
      label: "Download as Markdown",
      description: "Save as .md file with formatting",
      icon: Download,
      successIcon: Check,
      onClick: handleDownloadMd,
    },
    {
      key: "txt" as const,
      label: "Download as Text",
      description: "Save as plain .txt file",
      icon: FileText,
      successIcon: Check,
      onClick: handleDownloadTxt,
    },
  ];

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle className="text-base">Export Response</DialogTitle>
          <DialogDescription>
            Choose how you&apos;d like to export this council response.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-2 pt-2">
          {actions.map((action) => {
            const isSuccess = feedback === action.key;
            const Icon = isSuccess ? action.successIcon : action.icon;
            return (
              <Button
                key={action.key}
                variant="outline"
                className="w-full justify-start gap-3 h-auto py-3 px-4"
                onClick={action.onClick}
              >
                <Icon
                  className={`h-4 w-4 shrink-0 ${
                    isSuccess
                      ? "text-emerald-500"
                      : "text-muted-foreground"
                  }`}
                />
                <div className="text-left">
                  <p className="text-sm font-medium">
                    {isSuccess ? "Done!" : action.label}
                  </p>
                  <p className="text-[11px] text-muted-foreground">
                    {action.description}
                  </p>
                </div>
              </Button>
            );
          })}
        </div>
      </DialogContent>
    </Dialog>
  );
}
